#pragma once

#define BINNING_STAGE_BLOCK_SIZE 256
#define MAX_BIN_COUNT 256 // 128 x 128 pixel each bin
#define BIN_PIXEL_SIZE 128
#define BIN_PER_ROW 16

#define BIN_PIXEL_SIZE_LOG2 7 // 2^7 = 128

#define QUEUE_CHUNK_SIZE 256 //Byte
#define QUEUE_CHUNK_SIZE_UINT (QUEUE_CHUNK_SIZE / 4)

#define COARSE_RASTER_BLOCK_SIZE 256
#define MAX_TILE_COUNT 256
#define TILE_PIXEL_SIZE 8
#define TILE_PER_ROW ( (BIN_PIXEL_SIZE) / (TILE_PIXEL_SIZE) )

#define TILE_PIXEL_SIZE_LOG2 3 // 2^3 = 8

#define TILE_QUEUE_CHUNK_SIZE_UINT 512 // 2KB
#define TILE_QUEUE_CHUNK_SIZE (TILE_QUEUE_CHUNK_SIZE_UINT * 4)

#define TILE_QUEUE_ENTRY 4 // per tile

#define FINE_RASTER_BLOCK_SIZE 32
#define FINE_RASTER_PER_TILING_WORK_THREAD 32
#define FINE_RASTER_TILE_PER_BLOCK 4

#define AVERAGE_PRIMITIVE_CULLED_COUNT 4
#define AVERAGE_OVERDRAW 4 // 4x overdraw per pixel on average
#define AVERAGE_TRIANGLE_PER_TILE 512 // assume 1 full chunk
#define MAX_BINNING_WAVE 2046 